steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd tf-purge-app
      echo ""
      echo "*************** TERRAFORM INIT ******************"
      terraform init || exit 1

# Need to destroy, because TF doesn't spot changes in the code
# [START tf-destroy]
- id: 'tf destroy'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd tf-purge-app
      echo ""
      echo Selecting workspace...
      terraform workspace select dev-1  # parameterise this later
      echo ""
      echo "*************** TERRAFORM DESTROY ******************"
      terraform destroy -auto-approve
# [END tf-destroy]

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd tf-purge-app
      echo ""
      echo Selecting workspace...
      terraform workspace select dev-1  # parameterise this later
      echo ""
      echo "*************** TERRAFORM PLAN ******************"
      terraform plan || exit 1
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd tf-purge-app
      echo ""
      echo Selecting workspace...
      terraform workspace select dev-1  # parameterise this later
      echo ""
      echo "*************** TERRAFORM APPLY ******************"
      terraform apply -auto-approve
# [END tf-apply]